# Generated by Django 5.0.4 on 2025-10-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_category_alter_product_supplier'),
    ]

    operations = [
    ]
