# Generated by Django 5.0.4 on 2025-10-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
