# Generated by Django 5.0.4 on 2025-10-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_image_url1',
            new_name='profile_image_url',
        ),
    ]
